import "@/styles/globals.css";

import { type Metadata } from "next";
import { Bricolage_Grotesque, Hanken_Grotesk } from "next/font/google";

import { Provider } from "@/provider";
import { appBaseUrl } from "@/utils/url";

export const metadata: Metadata = {
  // Absolute URLs for the Open Graph cards (app/opengraph-image.tsx and each
  // booking link's own).
  metadataBase: new URL(appBaseUrl()),
  title: "Sara",
  description:
    "Run your business from the WhatsApp or Instagram chat you already use.",
  openGraph: { siteName: "Sara", type: "website" },
  twitter: { card: "summary_large_image" },
  // Generated by `yarn brand:generate` from the mark in src/utils/brand.ts.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: "/apple-touch-icon.png",
  },
};

// Type pairing from DESIGN.md: Bricolage Grotesque (display) + Hanken Grotesk (UI).
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  axes: ["opsz"],
  variable: "--font-bricolage",
});

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${bricolage.variable} ${hanken.variable}`}>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
