import { type MetadataRoute } from "next";

/** Home-screen install: the mark on its ink tile, generated by `yarn brand:generate`. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Sara",
    short_name: "Sara",
    description: "The admin side of your business, handled.",
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    icons: [
      { src: "/brand/sara-icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/brand/sara-icon-512.png", sizes: "512x512", type: "image/png" },
      { src: "/favicon.svg", sizes: "any", type: "image/svg+xml" },
    ],
  };
}
